# Reactive Debug Workflow Configuration
name: "reactive-debug"
description: "Systematic bug investigation and fixing. Will include a final step for the Knowledge Keeper to document the bug and its solution."
author: "joel"

# Critical variables load from config_source
config_source: "{project-root}/bmad/debug/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
date: system-generated

# Module path and component files
installed_path: "{project-root}/bmad/debug/workflows/reactive-debug"
template: false
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Tool Requirements
required_tools:
  - "Vercel API":
      description: "Required for fetching build logs and triggering deployments."
      link: "https://vercel.com/docs/rest-api"
