import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ExtensionBridgeProvider } from "@/components/providers/extension-bridge-provider";
import { SupabaseAuthProvider } from "@/components/providers/auth-provider";
import { QueryProvider } from "@/components/providers/query-provider";

// REMOVED: Direct Sentry import from layout.tsx
// Sentry is now initialized via instrumentation.ts which properly isolates
// Node.js runtime code from Edge Runtime bundles, preventing __dirname errors

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ExtensionBridgeProvider>
          <SupabaseAuthProvider>
            <QueryProvider>{children}</QueryProvider>
          </SupabaseAuthProvider>
        </ExtensionBridgeProvider>
      </body>
    </html>
  );
}
