import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SentryProvider } from "@/components/providers/sentry-provider";
import { ExtensionBridgeProvider } from "@/components/providers/extension-bridge-provider";
import { SupabaseAuthProvider } from "@/components/providers/auth-provider";
import { QueryProvider } from "@/components/providers/query-provider";

// Sentry initialization:
// - Server-side: via instrumentation.ts -> sentry.server.config.ts
// - Client-side: via SentryProvider -> sentry.client.config.ts
// - Edge Runtime: via instrumentation.ts -> sentry.edge.config.ts

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SentryProvider>
          <ExtensionBridgeProvider>
            <SupabaseAuthProvider>
              <QueryProvider>{children}</QueryProvider>
            </SupabaseAuthProvider>
          </ExtensionBridgeProvider>
        </SentryProvider>
      </body>
    </html>
  );
}
