name: 'query-knowledge-base'
description: 'This workflow allows for the direct querying of the bug/solution Archon RAG knowledge base. It can be invoked by a user for interactive searching or called by other workflows as an automated step to retrieve specific information.'
author: "joel"

# Critical variables load from config_source
config_source: "{project-root}/.bmad/debug/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Module path and component files
installed_path: "{project-root}/.bmad/debug/workflows/query-knowledge-base"
template: false
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

standalone: true
