name: 'get-intel'
description: 'Uses the Playwright backend to describe the current page''s layout and elements.'
author: "joel"

# Critical variables load from config_source
config_source: "{project-root}/.bmad/debug/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Module path and component files
installed_path: "{project-root}/.bmad/debug/workflows/get-intel"
template: false
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

standalone: false
