# Workflow for P.I. Playwright to Retrieve GitHub Actions Logs
name: "retrieve-github-actions-logs"
description: "Inspector Git-chell retrieves GitHub Actions build logs using the GitHub CLI."
author: "BMad"

# Critical variables load from config_source
config_source: "{project-root}/.bmad/bmb/config.yaml"
communication_language: "{config_source}:communication_language"
user_name: "{config_source}:user_name"
bmad_folder: "{config_source}:bmad_folder"

installed_path: "{project-root}/.bmad/debug/workflows/retrieve-github-actions-logs"
template: false
instructions: "{installed_path}/instructions.md"
