name: 'preventive-code-review'
description: 'This proactive workflow analyzes proposed code changes before they are committed, identifying potential bugs and suggesting improvements by cross-referencing against the Knowledge Keeper''s database of known anti-patterns and previous resolutions.'
author: "joel"

# Critical variables load from config_source
config_source: "{project-root}/.bmad/debug/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Module path and component files
installed_path: "{project-root}/.bmad/debug/workflows/preventive-code-review"
template: false
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

standalone: true
