name: 'circular-edit-intervention'
description: 'This workflow is designed to detect and break repetitive or circular debugging patterns, leveraging the Knowledge Keeper''s database to suggest alternative strategies and prevent infinite loops.'
author: "joel"

# Critical variables load from config_source
config_source: "{project-root}/.bmad/debug/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Module path and component files
installed_path: "{project-root}/.bmad/debug/workflows/circular-edit-intervention"
template: false
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

standalone: true
