name: 'test-coverage-gap'
description: 'This proactive workflow analyzes the codebase to identify areas with insufficient test coverage, then orchestrates the generation of new tests to fill those gaps and bolster the application''s quality.'
author: "joel"

# Critical variables load from config_source
config_source: "{project-root}/.bmad/debug/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Module path and component files
installed_path: "{project-root}/.bmad/debug/workflows/test-coverage-gap"
template: false
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

standalone: true
